service:
  name: dyn-dns

custom:
  hostname: ${opt:hostname}
  sharedSecret: ${opt:sharedSecret}
  hostedZoneId: ${opt:hostedZoneId}

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  runtime: java8
  memorySize: 512
  timeout: 29
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
      Resource: arn:aws:route53:::hostedzone/${self:custom.hostedZoneId}

package:
  artifact: build/libs/dyn-dns-all.jar

functions:
  dynDns:
    handler: com.adjectivecolournoun.dyndns.DynDnsHandler
    events:
      - http: POST update
    environment:
      HOSTNAME: ${self:custom.hostname}
      SHARED_SECRET: ${self:custom.sharedSecret}
      HOSTED_ZONE_ID: ${self:custom.hostedZoneId}